[package]
name = "go-parser-rs"
version = "0.1.0"
authors = ["Krouton <me+git@tokinia.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
